Meaningful return code for swallow()

diff --git a/pidswallow b/pidswallow
--- a/pidswallow
+++ b/pidswallow
@@ -28,9 +28,14 @@ vomit() {
 }
 
 swallow() {
+        # return values
+        # 0 -> Found and swallowed
+        # 1 -> No swallow able  node found.
+        # 2x -> xprop return a non zero exit code.(x is returned by xprop)
+        # 3 -> window lacks a _NET_WM_PID property.
         cwid="$1"
-        cpid="$(xprop _NET_WM_PID -id "$cwid" 2>/dev/null)" || return 1
-        [ "${cpid#*not found*}" != "$cpid" ] && return 1 # window didn't have _NET_WM_PID
+        cpid="$(xprop _NET_WM_PID -id "$cwid" 2>/dev/null)" || return "2$?"
+        [ "${cpid#*not found*}" != "$cpid" ] && return 3 # window didn't have _NET_WM_PID
         cpid="${cpid##* }"
         cname="$(ps -p "$cpid" -o comm=)"
         [ "${blacklist#* $cname }" != "$blacklist" ] && return 0
@@ -108,4 +113,3 @@ if [ -n "$*" ]; then
         echo "Unrecognized trailing option '$*'" >&2
         exit 1
 fi
-
